# Generated by Django 2.0.5 on 2018-05-22 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0002_himalayantimes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='himalayantimes',
            old_name='Source',
            new_name='source',
        ),
    ]
