# Generated by Django 2.0.5 on 2018-05-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0003_auto_20180522_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='himalayantimes',
            name='date',
            field=models.CharField(max_length=120),
        ),
    ]
